<div class="page-header"><h1>Projects</h1></div>

<a class="btn btn-default" href="projects/new" role="button"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Start New Project</a>

<p />

<?php
if (count($projects) > 0) {
?>
<div class="table-responsive">
    <table class="table table-striped table-hover table-bordered">
        <thead>
            <tr>
                <th class="col-md-2">Name</th>
            </tr>
        </thead>
        <tbody>

<?php
foreach ($projects as $project) {
?>
            <tr>
                <td><a href="projects/view/<?php echo $project->getId(); ?>"><?php echo $project->getName(); ?></a></td>
            </tr>
<?php
}
?>
        </tbody>
    </table>
</div>
<?php
}
?>
